var constants = {
    SYSTEM_USER: "SYSTEM",
    CURRENT_USER: "CURRENT_USER",
    USERS: "USERS",
    MIRROR_NAME: "MIRROR_NAME",
    MESSAGE_TYPES: {
        SAVE_DASHBOARD: "SAVE_DASHBOARD",
        SWITCH_USER: "SWITCH_USER",
        GET_USERS: "GET_USERS",
        RESTART_OFF: "RESTART_OFF",
        CAPTURE_USER: "CAPTURE_USER",
        USER_CAPTURED: "USER_CAPTURED",
        GET_USER_DASHBOARD: "GET_USER_DASHBOARD",
        USER_CAPTURE_FAIL: "USER_CAPTURE_FAIL",
        UPDATE_MIRROR_NAME: "UPDATE_MIRROR_NAME",
        DELETE_PROFILE: "DELETE_PROFILE"
    }
};

module.exports = constants;